veggie_recipe_book/recipes/urls.py
from django.urls import path, include
from .views import (AddRecipeView,
                    EditRecipeView,
                    DeleteRecipeView,
                    DetailRecipeView,
                    TypeOfRecipeView,
                    )

urlpatterns = [
    path('add/', AddRecipeView.as_view(), name='add_recipe'),
    path('edit/<int:pk>/edit/', EditRecipeView.as_view(), name='edit_recipe'),
    path('delete/<int:pk>/delete/', DeleteRecipeView.as_view(), name='delete_recipe'),
    path('details/<int:pk>/', DetailRecipeView.as_view(), name='details_recipe'),
    path('recipes-by-type/<str:recipe_type>/', TypeOfRecipeView.as_view(), name='recipes_by_type'),


    path('type/', include([
        path('desserts/', TypeOfRecipeView.as_view(), {'recipe_type': 'DS'}, name='desserts'),
        path('baked-goods/', TypeOfRecipeView.as_view(), {'recipe_type': 'BG'}, name='baked_goods'),
        path('sides/', TypeOfRecipeView.as_view(), {'recipe_type': 'SD'}, name='sides'),
        path('mains/', TypeOfRecipeView.as_view(), {'recipe_type': 'MN'}, name='mains'),
        path('drinks/', TypeOfRecipeView.as_view(), {'recipe_type': 'DR'}, name='drinks'),

    ])),
]

veggie_recipe_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('veggie_recipe_book.web.urls')),
    path('profile/', include('veggie_recipe_book.profiles.urls')),
    path('recipe/', include('veggie_recipe_book.recipes.urls')),
    path('social/', include('veggie_recipe_book.social.urls')),
    path('converter/', include('veggie_recipe_book.unit_converter.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

veggie_recipe_book/recipes/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth import get_user_model

from veggie_recipe_book.recipes.validators import validate_image_size

UserModel = get_user_model()


class Recipe(models.Model):

    MIN_RECIPE_TITLE_LENGTH = 2
    MAX_RECIPE_TITLE_LENGTH = 75

    class RecipeType(models.TextChoices):
        BAKED_GOODS = 'BG', 'Baked Goods'
        DESSERTS = 'DS', 'Desserts'
        SIDES = 'SD', 'Sides'
        MAINS = 'MN', 'Mains'
        DRINKS = 'DR', 'Drinks'

        @classmethod
        def max_length(cls):
            return max(len(choice[0]) for choice in cls.choices)

    MAX_RECIPE_TYPE_LENGTH = RecipeType.max_length()

    title = models.CharField(max_length=MAX_RECIPE_TITLE_LENGTH,
                             unique=True,
                             blank=False,
                             null=False,
                             validators=[MinLengthValidator(MIN_RECIPE_TITLE_LENGTH,
                                                            message=f'Title cannot be fewer '
                                                                    f'than {MIN_RECIPE_TITLE_LENGTH} letters long'
                                                            ),
                                         ],
                             )
    recipe_type = models.CharField(max_length=MAX_RECIPE_TYPE_LENGTH,
                                   choices=RecipeType.choices,
                                   blank=False,
                                   null=False,
                                   )
    picture = models.ImageField(upload_to='recipe_pictures/',
                                blank=True,
                                null=True,
                                validators=[validate_image_size,
                                            ],
                                )
    ingredients_text = models.TextField(blank=False,
                                        null=False,
                                        )
    description = models.TextField(blank=False,
                                   null=False,
                                   )
    servings = models.IntegerField(blank=False,
                                   null=False,
                                   )
    is_private = models.BooleanField(default=False,
                                     blank=False,
                                     null=False,
                                     )
    created_at = models.DateTimeField(auto_now_add=True,
                                      )
    edited_at = models.DateTimeField(auto_now=True,
                                     )
    author = models.ForeignKey(UserModel,
                               on_delete=models.CASCADE,
                               )

    def __str__(self):
        return self.title

    def clean(self):
        super().clean()
        if self.ingredients_text:
            ingredients_list = self.ingredients_text.strip()
            self.ingredients = ingredients_list


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               )
    content = models.TextField(blank=False,
                               null=False,
                               )
    created_at = models.DateTimeField(auto_now_add=True,
                                      )
    edited_at = models.DateTimeField(auto_now=True,
                                     )
    user = models.ForeignKey(UserModel,
                             on_delete=models.CASCADE,
                             )

    def clean(self):
        if not self.content.strip():
            raise ValidationError("Comment cannot be empty!")


class Like(models.Model):
    user = models.ForeignKey(UserModel,
                             on_delete=models.CASCADE,
                             )
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user', 'recipe']

    def __str__(self):
        return f'{self.user.username} liked {self.recipe.title}'

veggie_recipe_book/recipes/forms.py
from django import forms

from veggie_recipe_book.recipes.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'recipe_type', 'picture', 'ingredients_text', 'description', 'servings',
                  'is_private', ]
        widgets = {
            'ingredients_text': forms.Textarea(attrs={'placeholder': 'Please enter each ingredient on a new line.'},
                                               ),
            'title': forms.TextInput(attrs={'placeholder': 'Recipe Name'},
                                     ),
            'description': forms.Textarea(attrs={'placeholder': 'Your recipe'},
                                          ),
        }

veggie_recipe_book/recipes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.urls import reverse_lazy, reverse
from veggie_recipe_book.recipes.forms import RecipeForm
from veggie_recipe_book.recipes.models import Recipe, Comment, Like
from veggie_recipe_book.social.forms import CommentForm


class AddRecipeView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/add_recipe.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(reverse('details_recipe', kwargs={'pk': self.object.pk}))


class EditRecipeView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/edit_recipe.html'

    def get_success_url(self):
        return reverse('details_recipe', kwargs={'pk': self.object.pk})

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author


class DeleteRecipeView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Recipe
    template_name = 'recipes/recipe_confirm_delete.html'

    def get_success_url(self):
        return reverse('details_profile', kwargs={'pk': self.object.author.pk})

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author


class DetailRecipeView(DetailView):
    model = Recipe
    template_name = 'recipes/detail_recipe.html'

    def get_object(self, queryset=None):
        queryset = self.get_queryset()
        recipe = get_object_or_404(queryset, pk=self.kwargs.get('pk'))
        return recipe

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.get_object()
        recipe_type = recipe.recipe_type

        comments = Comment.objects.filter(recipe=recipe)
        context['comments'] = comments
        context['comment_form'] = CommentForm() if self.request.user.is_authenticated else None

        context['has_liked'] = (Like.objects.filter(recipe=recipe, user=self.request.user).exists()) if self.request.user.is_authenticated else False
        total_likes = (Like.objects.filter(recipe=recipe)
                       .count())
        context['total_likes'] = total_likes

        context['recipe_type'] = recipe_type

        return context


class TypeOfRecipeView(ListView):
    template_name = 'recipes/recipes_by_type.html'
    context_object_name = 'recipes'
    paginate_by = 12

    def get_queryset(self):
        recipe_type = self.kwargs.get('recipe_type')
        return ((Recipe.objects
                .filter(recipe_type=recipe_type)
                .filter(is_private=False))
                .order_by('-created_at'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        recipe_type = self.kwargs.get('recipe_type')
        recipe_type_display = dict(Recipe.RecipeType.choices)[recipe_type]
        context['recipe_type_display'] = recipe_type_display

        return context

templates/recipes/add_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="add-recipe">
    <h2>Add Recipe</h2>
    
    <form action="{% url 'add_recipe' %}" method="post" enctype="multipart/form-data">
      {{ form.as_p }}
      <button type="submit">Save</button>
        
      {% csrf_token %}

    </form>
  </div>
{% endblock %}

templates/recipes/detail_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="in-line-title-like">
    
  <div class="detail-recipe">
  
    <h2>{{ recipe.title|lower|capfirst }}
      <div class="likes">
         {% if user.is_authenticated %}
            {% if has_liked %}
                <a href="{% url 'recipe_unlike' recipe_id=recipe.id %}" class="like-btn liked"><i class="fas fa-heart"></i></a>
            {% else %}
                <a href="{% url 'recipe_like' recipe_id=recipe.id %}" class="like-btn"><i class="far fa-heart"></i></a>
            {% endif %}
             <span>{{ total_likes }}</span>
         {% endif %}
         
      </div>
    </h2>

    <div class="edit-delete-recipe-buttons">
      {% if user.is_authenticated and user == recipe.author %}
          <a href="{% url 'edit_recipe' pk=recipe.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
          <a href="{% url 'delete_recipe' pk=recipe.id %}"><i class="fa-solid fa-trash"></i></a>
      {% endif %}
    </div>
  
    <img class="profile-picture" height="250px" src="{% if recipe.picture %}{{ recipe.picture.url }}{% else %}{% static 'images/no_image_avb.png' %}{% endif %}" alt="picture of {{ recipe.title }}" />
    
    <div class="info">
      <p>Recipe Type: <a href="{% url 'recipes_by_type' recipe_type %}">{{ recipe.get_recipe_type_display }}</a></p>
      <p>Servings: {{ recipe.servings }}</p>
      <p>Created by: <a href="{% url 'details_profile' pk=recipe.author.pk %}">{{ recipe.author.username }}</a></p>
    </div>
  
    <div class="sections-container">
      <div class="section ingredients">
        <h3>Ingredients</h3> <a href="{% url 'unit_converter' %}"><i class="fa-solid fa-calculator"></i></a>

        <ul>
          {% include 'partials/ingredient_list.html' %}
        </ul>
      </div>
    
      <div class="section instructions">
        <h3>Instructions</h3>
        <div class="instructions-content">
          <p>{{ recipe.description }}</p>
        </div>
      </div>
    </div>
  
    {% if user.is_authenticated %}

    <div class="add-comment">
      <form method="post" action="{% url 'add_comment' recipe.pk %}">
        {{ comment_form.as_p }}
        <button class="comment-btn" type="submit">Submit Comment</button>
        {% csrf_token %}
      </form>
     </div>
   {% endif %}
  
      <div class="comments">
       <h3>Comments</h3>
       {% if comments %}
         <ul>
          {% for comment in comments %}
            <li>
              <blockquote>
                <p>{{ comment.content }}</p>
                <footer>- <a href="{% url 'details_profile' pk=comment.user.pk %}">{{ comment.user.username }}</a></footer>
              </blockquote>
                </li>
              {% endfor %}
              </ul>
       {% else %}
             <p>No comments yet.</p>
       {% endif %}
      </div>
  
  </div>
</div>
{% endblock %}

templates/recipes/edit_ingredient_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
<div class="edit-ingredient-form">

<h2>Edit Ingredient</h2>
    
<form action="{% url 'edit_ingredient' pk=object.pk recipe_pk=object.recipe.pk %}" method="post">
    
    {{ form.as_p }}
    
    <button type="submit">Save</button>
    
    {% csrf_token %}

    
</form>
    
</div>
    
{% endblock %}

templates/recipes/edit_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="edit-recipe"> 
  <h2>Edit Recipe</h2>
  <form action="{% url 'edit_recipe' pk=object.pk %}" method="post" enctype="multipart/form-data">
  
    {{ form.as_p }}

    <button type="submit">Update Recipe</button>
  
    {% csrf_token %}
  </form>
</div>

{% endblock %}

templates/recipes/recipe_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="delete-recipe">

    <h2>Are you sure you want to delete {{ recipe.title }}?</h2>
    
    <form action="{% url 'delete_recipe' pk=recipe.pk %}" method="post">
        <button class="delete-button" type="submit">Delete</button>
        
        {% csrf_token %}
    </form>
    
    <a class="back-button" href="{% url 'details_recipe' pk=object.pk %}">Cancel</a>
</div>
{% endblock %}

templates/recipes/recipes_by_type.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2> {{ recipe_type_display }}: </h2>
    
    {% include 'partials/recipes_type_of_food_display.html' %}
    
    {% include 'partials/page_nav.html' %}

{% endblock %}